### ISSUE TITLE
completely disabling animations can cause problems

### ISSUE THREAD

**Issue by sumyungguy** [gagarine/no-transition#11]
The addon works by inserting these styles to disable animations:
```
 /*CSS transition*/
  transition: none !important;
  /*CSS animations*/
  animation: none !important;
```

I'm not an expert, but I've found it might be useful to consider some of these additional types:

```
/*CSS transitions*/
 -o-transition-property: none !important;
 -moz-transition-property: none !important;
 -ms-transition-property: none !important;
 -webkit-transition-property: none !important;
 transition-property: none !important;
 /*CSS transforms*/
 -o-transform: none !important;
 -moz-transform: none !important;
 -ms-transform: none !important;
 -webkit-transform: none !important;
 transform: none !important;
 /*CSS animations*/
 -webkit-animation: none !important;
 -moz-animation: none !important;
 -o-animation: none !important;
 -ms-animation: none !important;
 animation: none !important;
```

I'm not sure which of them may be necessary. There's some discussion about it here:
https://stackoverflow.com/questions/11131875/what-is-the-cleanest-way-to-disable-css-transition-effects-temporarily/16575811#16575811

Also, sometimes completely disabling animations can cause problems. See:
https://www.reddit.com/r/firefox/comments/37hw8o/how_to_disable_all_animations/
Which suggests the alternative:
``` 
animation-delay: 0ms !important;
animation-duration: 0ms !important;
transition: none !important;
```
And these bookmarklets which offer a choice of killing or just pausing:
https://github.com/stephen322/cssanim-bookmarklet

**Comment by gagarine** [comment]
For your first comment: We don't need browser prefix because we know the browser (Firefox...). So this don't need to change.

For your point about "disabling animations can cause problem". This is interesting and I will say certainly true....  I will love to have a concrete example to test it.

**Comment by gagarine** [comment]
This was a problem for example on https://www.linkedin.com with the top bar...
