### ISSUE TITLE
Problem with google login

### ISSUE THREAD

**Issue by gagarine** [gagarine/no-transition#13]
On https://accounts.google.com/signin/v2/ field stay in gray state.

**Comment by gwarser** [comment]
http://www.ilewazy.pl/szklanka-ryzu-jasminowego-2 when I click "Do kalkulatora" green button near top right corner - dialog should slide down.

Cannot confirm this one, may be on my side only:
When I am logged into endomodo.com, using facebook, then restart browser, then when I try to load https://www.endomondo.com/home first time in session, I see narrow progress line on top and then nothing happens. 

I hope this will fix this issue:

```
animation-delay: 1ms !important;
animation-duration: 0ms !important;
transition-delay: 1ms !important;
transition-duration: 0ms !important;
```

I'm not using your extension. [This](https://greasyfork.org/en/scripts/19654-animalquery/code) is my code

**Comment by gwarser** [comment]
`transition-delay: 1ms !important;` is breaking youtube "Theater" mode - video is not expanded in width :/
Without this line, google login page is broken.

**Comment by gagarine** [comment]
@gwarser thanks for your input. I will test that ASAP.
