### ISSUE TITLE
Why it's been removed from Firefox addons catalogue?

### ISSUE THREAD

**Issue by heltua** [gagarine/no-transition#35]
Why it's been removed from Firefox addons catalogue? I used this addon mainly for getting rid of the idiotic recaptcha fading. Just reinstalled my FF but couldn't find this important helper. Thank you!

**Comment by gagarine** [comment]
I don’t have the time to maintain it and don’t use it myself anymore.

I deleted the adding and I don’t have a dev account anymore for Mozilla services. 

Thanks for your understanding. Feel free to fork and republish.
