### ISSUE TITLE
Not compatible with Firefox ESR 52.2.1

### ISSUE THREAD

**Issue by happysurf** [gagarine/no-transition#6]
This morning I tried the extension on my Firefox ESR 52.2.1 on XP and doesn't work (tested on links found on your AMO addon page).
On Firefox 55 beta works fine.
Maybe you must correct the minimum version compatibility.

**Comment by gagarine** [comment]
Thanks for the report. 
On the AMO backend this is what I have:
![screen shot 2017-07-10 at 22 44 01](https://user-images.githubusercontent.com/164074/28039083-504093ee-65c1-11e7-9aa6-9dec6f088658.png)

What you say "it doesn't work" what append exactly? You can't install it?

**Comment by happysurf** [comment]
I can install the extension but then the CSS3 animation remain still active.
Tested on:
- https://www.w3schools.com/css/css3_transitions.asp
- https://www.w3schools.com/css/css3_animations.asp

**Comment by gagarine** [comment]
I see. It's certainly one API that I'm using. I will raise the compatibility for the moment. If their is a demand for Firefox ESR I will look into this bug.
